//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright 2025 the original author or authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by diegen. DO NOT EDIT.

package testresources

import (
	fmtx "fmt"
	osx "os"
	reflectx "reflect"

	cmp "github.com/google/go-cmp/cmp"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	unstructured "k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
	runtime "k8s.io/apimachinery/pkg/runtime"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	"k8s.io/apimachinery/pkg/util/json"
	jsonpath "k8s.io/client-go/util/jsonpath"
	v1 "reconciler.io/dies/apis/meta/v1"
	patch "reconciler.io/dies/patch"
	yaml "sigs.k8s.io/yaml"
)

var ConditionDuckBlank = (&ConditionDuckDie{}).DieFeed(ConditionDuck{})

type ConditionDuckDie struct {
	v1.FrozenObjectMeta
	mutable bool
	r       ConditionDuck
	seal    ConditionDuck
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ConditionDuckDie) DieImmutable(immutable bool) *ConditionDuckDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ConditionDuckDie) DieFeed(r ConditionDuck) *ConditionDuckDie {
	if d.mutable {
		d.FrozenObjectMeta = v1.FreezeObjectMeta(r.ObjectMeta)
		d.r = r
		return d
	}
	return &ConditionDuckDie{
		FrozenObjectMeta: v1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
		seal:             d.seal,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ConditionDuckDie) DieFeedPtr(r *ConditionDuck) *ConditionDuckDie {
	if r == nil {
		r = &ConditionDuck{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *ConditionDuckDie) DieFeedJSON(j []byte) *ConditionDuckDie {
	r := ConditionDuck{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *ConditionDuckDie) DieFeedYAML(y []byte) *ConditionDuckDie {
	r := ConditionDuck{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *ConditionDuckDie) DieFeedYAMLFile(name string) *ConditionDuckDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ConditionDuckDie) DieFeedRawExtension(raw runtime.RawExtension) *ConditionDuckDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *ConditionDuckDie) DieRelease() ConditionDuck {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ConditionDuckDie) DieReleasePtr() *ConditionDuck {
	r := d.DieRelease()
	return &r
}

// DieReleaseUnstructured returns the resource managed by the die as an unstructured object. Panics on error.
func (d *ConditionDuckDie) DieReleaseUnstructured() *unstructured.Unstructured {
	r := d.DieReleasePtr()
	u, err := runtime.DefaultUnstructuredConverter.ToUnstructured(r)
	if err != nil {
		panic(err)
	}
	return &unstructured.Unstructured{
		Object: u,
	}
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *ConditionDuckDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *ConditionDuckDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ConditionDuckDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ConditionDuckDie) DieStamp(fn func(r *ConditionDuck)) *ConditionDuckDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type or a pointer to that type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *ConditionDuckDie) DieStampAt(jp string, fn interface{}) *ConditionDuckDie {
	return d.DieStamp(func(r *ConditionDuck) {
		if ni := reflectx.ValueOf(fn).Type().NumIn(); ni != 1 {
			panic(fmtx.Errorf("callback function must have 1 input parameters, found %d", ni))
		}
		if no := reflectx.ValueOf(fn).Type().NumOut(); no != 0 {
			panic(fmtx.Errorf("callback function must have 0 output parameters, found %d", no))
		}

		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			arg0t := reflectx.ValueOf(fn).Type().In(0)

			var args []reflectx.Value
			if cv.Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv}
			} else if cv.CanAddr() && cv.Addr().Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv.Addr()}
			} else {
				panic(fmtx.Errorf("callback function must accept value of type %q, found type %q", cv.Type(), arg0t))
			}

			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *ConditionDuckDie) DieWith(fns ...func(d *ConditionDuckDie)) *ConditionDuckDie {
	nd := ConditionDuckBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	for _, fn := range fns {
		if fn != nil {
			fn(nd)
		}
	}
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ConditionDuckDie) DeepCopy() *ConditionDuckDie {
	r := *d.r.DeepCopy()
	return &ConditionDuckDie{
		FrozenObjectMeta: v1.FreezeObjectMeta(r.ObjectMeta),
		mutable:          d.mutable,
		r:                r,
		seal:             d.seal,
	}
}

// DieSeal returns a new die for the current die's state that is sealed for comparison in future diff and patch operations.
func (d *ConditionDuckDie) DieSeal() *ConditionDuckDie {
	return d.DieSealFeed(d.r)
}

// DieSealFeed returns a new die for the current die's state that uses a specific resource for comparison in future diff and patch operations.
func (d *ConditionDuckDie) DieSealFeed(r ConditionDuck) *ConditionDuckDie {
	if !d.mutable {
		d = d.DeepCopy()
	}
	d.seal = *r.DeepCopy()
	return d
}

// DieSealFeedPtr returns a new die for the current die's state that uses a specific resource pointer for comparison in future diff and patch operations. If the resource is nil, the empty value is used instead.
func (d *ConditionDuckDie) DieSealFeedPtr(r *ConditionDuck) *ConditionDuckDie {
	if r == nil {
		r = &ConditionDuck{}
	}
	return d.DieSealFeed(*r)
}

// DieSealRelease returns the sealed resource managed by the die.
func (d *ConditionDuckDie) DieSealRelease() ConditionDuck {
	return *d.seal.DeepCopy()
}

// DieSealReleasePtr returns the sealed resource pointer managed by the die.
func (d *ConditionDuckDie) DieSealReleasePtr() *ConditionDuck {
	r := d.DieSealRelease()
	return &r
}

// DieDiff uses cmp.Diff to compare the current value of the die with the sealed value.
func (d *ConditionDuckDie) DieDiff(opts ...cmp.Option) string {
	return cmp.Diff(d.seal, d.r, opts...)
}

// DiePatch generates a patch between the current value of the die and the sealed value.
func (d *ConditionDuckDie) DiePatch(patchType types.PatchType) ([]byte, error) {
	return patch.Create(d.seal, d.r, patchType)
}

var _ runtime.Object = (*ConditionDuckDie)(nil)

func (d *ConditionDuckDie) DeepCopyObject() runtime.Object {
	return d.r.DeepCopy()
}

func (d *ConditionDuckDie) GetObjectKind() schema.ObjectKind {
	r := d.DieRelease()
	return r.GetObjectKind()
}

func (d *ConditionDuckDie) MarshalJSON() ([]byte, error) {
	return json.Marshal(d.r)
}

func (d *ConditionDuckDie) UnmarshalJSON(b []byte) error {
	if !d.mutable {
		return fmtx.Errorf("cannot unmarshal into immutable dies, create a mutable version first")
	}
	resource := &ConditionDuck{}
	err := json.Unmarshal(b, resource)
	*d = *d.DieFeed(*resource)
	return err
}

// APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources
func (d *ConditionDuckDie) APIVersion(v string) *ConditionDuckDie {
	return d.DieStamp(func(r *ConditionDuck) {
		r.APIVersion = v
	})
}

// Kind is a string value representing the REST resource this object represents. Servers may infer this from the endpoint the client submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds
func (d *ConditionDuckDie) Kind(v string) *ConditionDuckDie {
	return d.DieStamp(func(r *ConditionDuck) {
		r.Kind = v
	})
}

// TypeMetadata standard object's type metadata.
func (d *ConditionDuckDie) TypeMetadata(v metav1.TypeMeta) *ConditionDuckDie {
	return d.DieStamp(func(r *ConditionDuck) {
		r.TypeMeta = v
	})
}

// TypeMetadataDie stamps the resource's TypeMeta field with a mutable die.
func (d *ConditionDuckDie) TypeMetadataDie(fn func(d *v1.TypeMetaDie)) *ConditionDuckDie {
	return d.DieStamp(func(r *ConditionDuck) {
		d := v1.TypeMetaBlank.DieImmutable(false).DieFeed(r.TypeMeta)
		fn(d)
		r.TypeMeta = d.DieRelease()
	})
}

// Metadata standard object's metadata.
func (d *ConditionDuckDie) Metadata(v metav1.ObjectMeta) *ConditionDuckDie {
	return d.DieStamp(func(r *ConditionDuck) {
		r.ObjectMeta = v
	})
}

// MetadataDie stamps the resource's ObjectMeta field with a mutable die.
func (d *ConditionDuckDie) MetadataDie(fn func(d *v1.ObjectMetaDie)) *ConditionDuckDie {
	return d.DieStamp(func(r *ConditionDuck) {
		d := v1.ObjectMetaBlank.DieImmutable(false).DieFeed(r.ObjectMeta)
		fn(d)
		r.ObjectMeta = d.DieRelease()
	})
}

// StatusDie stamps the resource's status field with a mutable die.
func (d *ConditionDuckDie) StatusDie(fn func(d *ConditionDuckStatusDie)) *ConditionDuckDie {
	return d.DieStamp(func(r *ConditionDuck) {
		d := ConditionDuckStatusBlank.DieImmutable(false).DieFeed(r.Status)
		fn(d)
		r.Status = d.DieRelease()
	})
}

func (d *ConditionDuckDie) Status(v ConditionDuckStatus) *ConditionDuckDie {
	return d.DieStamp(func(r *ConditionDuck) {
		r.Status = v
	})
}

var ConditionDuckStatusBlank = (&ConditionDuckStatusDie{}).DieFeed(ConditionDuckStatus{})

type ConditionDuckStatusDie struct {
	mutable bool
	r       ConditionDuckStatus
	seal    ConditionDuckStatus
}

// DieImmutable returns a new die for the current die's state that is either mutable (`false`) or immutable (`true`).
func (d *ConditionDuckStatusDie) DieImmutable(immutable bool) *ConditionDuckStatusDie {
	if d.mutable == !immutable {
		return d
	}
	d = d.DeepCopy()
	d.mutable = !immutable
	return d
}

// DieFeed returns a new die with the provided resource.
func (d *ConditionDuckStatusDie) DieFeed(r ConditionDuckStatus) *ConditionDuckStatusDie {
	if d.mutable {
		d.r = r
		return d
	}
	return &ConditionDuckStatusDie{
		mutable: d.mutable,
		r:       r,
		seal:    d.seal,
	}
}

// DieFeedPtr returns a new die with the provided resource pointer. If the resource is nil, the empty value is used instead.
func (d *ConditionDuckStatusDie) DieFeedPtr(r *ConditionDuckStatus) *ConditionDuckStatusDie {
	if r == nil {
		r = &ConditionDuckStatus{}
	}
	return d.DieFeed(*r)
}

// DieFeedJSON returns a new die with the provided JSON. Panics on error.
func (d *ConditionDuckStatusDie) DieFeedJSON(j []byte) *ConditionDuckStatusDie {
	r := ConditionDuckStatus{}
	if err := json.Unmarshal(j, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAML returns a new die with the provided YAML. Panics on error.
func (d *ConditionDuckStatusDie) DieFeedYAML(y []byte) *ConditionDuckStatusDie {
	r := ConditionDuckStatus{}
	if err := yaml.Unmarshal(y, &r); err != nil {
		panic(err)
	}
	return d.DieFeed(r)
}

// DieFeedYAMLFile returns a new die loading YAML from a file path. Panics on error.
func (d *ConditionDuckStatusDie) DieFeedYAMLFile(name string) *ConditionDuckStatusDie {
	y, err := osx.ReadFile(name)
	if err != nil {
		panic(err)
	}
	return d.DieFeedYAML(y)
}

// DieFeedRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ConditionDuckStatusDie) DieFeedRawExtension(raw runtime.RawExtension) *ConditionDuckStatusDie {
	j, err := json.Marshal(raw)
	if err != nil {
		panic(err)
	}
	return d.DieFeedJSON(j)
}

// DieRelease returns the resource managed by the die.
func (d *ConditionDuckStatusDie) DieRelease() ConditionDuckStatus {
	if d.mutable {
		return d.r
	}
	return *d.r.DeepCopy()
}

// DieReleasePtr returns a pointer to the resource managed by the die.
func (d *ConditionDuckStatusDie) DieReleasePtr() *ConditionDuckStatus {
	r := d.DieRelease()
	return &r
}

// DieReleaseJSON returns the resource managed by the die as JSON. Panics on error.
func (d *ConditionDuckStatusDie) DieReleaseJSON() []byte {
	r := d.DieReleasePtr()
	j, err := json.Marshal(r)
	if err != nil {
		panic(err)
	}
	return j
}

// DieReleaseYAML returns the resource managed by the die as YAML. Panics on error.
func (d *ConditionDuckStatusDie) DieReleaseYAML() []byte {
	r := d.DieReleasePtr()
	y, err := yaml.Marshal(r)
	if err != nil {
		panic(err)
	}
	return y
}

// DieReleaseRawExtension returns the resource managed by the die as an raw extension. Panics on error.
func (d *ConditionDuckStatusDie) DieReleaseRawExtension() runtime.RawExtension {
	j := d.DieReleaseJSON()
	raw := runtime.RawExtension{}
	if err := json.Unmarshal(j, &raw); err != nil {
		panic(err)
	}
	return raw
}

// DieStamp returns a new die with the resource passed to the callback function. The resource is mutable.
func (d *ConditionDuckStatusDie) DieStamp(fn func(r *ConditionDuckStatus)) *ConditionDuckStatusDie {
	r := d.DieRelease()
	fn(&r)
	return d.DieFeed(r)
}

// Experimental: DieStampAt uses a JSON path (http://goessner.net/articles/JsonPath/) expression to stamp portions of the resource. The callback is invoked with each JSON path match. Panics if the callback function does not accept a single argument of the same type or a pointer to that type as found on the resource at the target location.
//
// Future iterations will improve type coercion from the resource to the callback argument.
func (d *ConditionDuckStatusDie) DieStampAt(jp string, fn interface{}) *ConditionDuckStatusDie {
	return d.DieStamp(func(r *ConditionDuckStatus) {
		if ni := reflectx.ValueOf(fn).Type().NumIn(); ni != 1 {
			panic(fmtx.Errorf("callback function must have 1 input parameters, found %d", ni))
		}
		if no := reflectx.ValueOf(fn).Type().NumOut(); no != 0 {
			panic(fmtx.Errorf("callback function must have 0 output parameters, found %d", no))
		}

		cp := jsonpath.New("")
		if err := cp.Parse(fmtx.Sprintf("{%s}", jp)); err != nil {
			panic(err)
		}
		cr, err := cp.FindResults(r)
		if err != nil {
			// errors are expected if a path is not found
			return
		}
		for _, cv := range cr[0] {
			arg0t := reflectx.ValueOf(fn).Type().In(0)

			var args []reflectx.Value
			if cv.Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv}
			} else if cv.CanAddr() && cv.Addr().Type().AssignableTo(arg0t) {
				args = []reflectx.Value{cv.Addr()}
			} else {
				panic(fmtx.Errorf("callback function must accept value of type %q, found type %q", cv.Type(), arg0t))
			}

			reflectx.ValueOf(fn).Call(args)
		}
	})
}

// DieWith returns a new die after passing the current die to the callback function. The passed die is mutable.
func (d *ConditionDuckStatusDie) DieWith(fns ...func(d *ConditionDuckStatusDie)) *ConditionDuckStatusDie {
	nd := ConditionDuckStatusBlank.DieFeed(d.DieRelease()).DieImmutable(false)
	for _, fn := range fns {
		if fn != nil {
			fn(nd)
		}
	}
	return d.DieFeed(nd.DieRelease())
}

// DeepCopy returns a new die with equivalent state. Useful for snapshotting a mutable die.
func (d *ConditionDuckStatusDie) DeepCopy() *ConditionDuckStatusDie {
	r := *d.r.DeepCopy()
	return &ConditionDuckStatusDie{
		mutable: d.mutable,
		r:       r,
		seal:    d.seal,
	}
}

// DieSeal returns a new die for the current die's state that is sealed for comparison in future diff and patch operations.
func (d *ConditionDuckStatusDie) DieSeal() *ConditionDuckStatusDie {
	return d.DieSealFeed(d.r)
}

// DieSealFeed returns a new die for the current die's state that uses a specific resource for comparison in future diff and patch operations.
func (d *ConditionDuckStatusDie) DieSealFeed(r ConditionDuckStatus) *ConditionDuckStatusDie {
	if !d.mutable {
		d = d.DeepCopy()
	}
	d.seal = *r.DeepCopy()
	return d
}

// DieSealFeedPtr returns a new die for the current die's state that uses a specific resource pointer for comparison in future diff and patch operations. If the resource is nil, the empty value is used instead.
func (d *ConditionDuckStatusDie) DieSealFeedPtr(r *ConditionDuckStatus) *ConditionDuckStatusDie {
	if r == nil {
		r = &ConditionDuckStatus{}
	}
	return d.DieSealFeed(*r)
}

// DieSealRelease returns the sealed resource managed by the die.
func (d *ConditionDuckStatusDie) DieSealRelease() ConditionDuckStatus {
	return *d.seal.DeepCopy()
}

// DieSealReleasePtr returns the sealed resource pointer managed by the die.
func (d *ConditionDuckStatusDie) DieSealReleasePtr() *ConditionDuckStatus {
	r := d.DieSealRelease()
	return &r
}

// DieDiff uses cmp.Diff to compare the current value of the die with the sealed value.
func (d *ConditionDuckStatusDie) DieDiff(opts ...cmp.Option) string {
	return cmp.Diff(d.seal, d.r, opts...)
}

// DiePatch generates a patch between the current value of the die and the sealed value.
func (d *ConditionDuckStatusDie) DiePatch(patchType types.PatchType) ([]byte, error) {
	return patch.Create(d.seal, d.r, patchType)
}

// ConditionDie mutates a single item in Conditions matched by the nested field Type, appending a new item if no match is found.
func (d *ConditionDuckStatusDie) ConditionDie(v string, fn func(d *v1.ConditionDie)) *ConditionDuckStatusDie {
	return d.DieStamp(func(r *ConditionDuckStatus) {
		for i := range r.Conditions {
			if v == r.Conditions[i].Type {
				d := v1.ConditionBlank.DieImmutable(false).DieFeed(r.Conditions[i])
				fn(d)
				r.Conditions[i] = d.DieRelease()
				return
			}
		}

		d := v1.ConditionBlank.DieImmutable(false).DieFeed(metav1.Condition{Type: v})
		fn(d)
		r.Conditions = append(r.Conditions, d.DieRelease())
	})
}

func (d *ConditionDuckStatusDie) ObservedGeneration(v int64) *ConditionDuckStatusDie {
	return d.DieStamp(func(r *ConditionDuckStatus) {
		r.ObservedGeneration = v
	})
}

func (d *ConditionDuckStatusDie) Conditions(v ...metav1.Condition) *ConditionDuckStatusDie {
	return d.DieStamp(func(r *ConditionDuckStatus) {
		r.Conditions = v
	})
}
