# This rule is not used by the project ducks itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to duck.reconciler.io resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: ducks
    app.kubernetes.io/managed-by: kustomize
  name: ducktype-viewer-role
rules:
- apiGroups:
  - duck.reconciler.io
  resources:
  - ducktypes
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - duck.reconciler.io
  resources:
  - ducktypes/status
  verbs:
  - get
