---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ducks.reconciler.io
  resources:
  - clusterducks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ducks.reconciler.io
  resources:
  - clusterducks/finalizers
  verbs:
  - update
- apiGroups:
  - ducks.reconciler.io
  resources:
  - clusterducks/status
  verbs:
  - get
  - patch
  - update
