name: CI

on:
  push:
    branches:
    - '**'
    - '!dependabot/**'
    tags:
    # semver tags
    - 'v[0-9]+\.[0-9]+\.[0-9]+-?**'
  pull_request: {}

env:
  IMGPKG: go run -modfile hack/imgpkg/go.mod carvel.dev/imgpkg/cmd/imgpkg
  KAPP: go run -modfile hack/kapp/go.mod carvel.dev/kapp/cmd/kapp
  KBLD: go run -modfile hack/kbld/go.mod carvel.dev/kbld/cmd/kbld
  KO: go run -modfile hack/ko/go.mod github.com/google/ko

jobs:

  unit:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache-dependency-path: '**/*.sum'
    - name: Test
      run: make test
    - name: Report coverage
      uses: codecov/codecov-action@v6
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
    - name: Disallow generated drift
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail

        git diff --exit-code .

  stage:
    name: Stage
    runs-on: ubuntu-latest
    env:
      REGISTRY_NAME: registry.local
      KO_DOCKER_REPO: registry.local/ducks
      KO_PLATFORMS: linux/amd64,linux/arm64
      BUNDLE: registry.local/ducks/bundle
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache-dependency-path: '**/*.sum'
    - name: Local Registry
      uses: reconcilerio/registry@v1
      id: registry
      with:
        hostname: ${{ env.REGISTRY_NAME }}
    - name: Build all platforms for tags
      if: startsWith(github.ref, 'refs/tags/')
      run: |
        echo "KO_PLATFORMS=all" >> $GITHUB_ENV
    - name: Build
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail

        scratch=$(mktemp -d -t bundle.XXXX)
        mkdir -p "${scratch}/.imgpkg"
        mkdir -p "${scratch}/config"

        cp LICENSE "${scratch}/LICENSE"

        echo "##[group]Build"
          cat hack/boilerplate.yaml.txt > "${scratch}/config/reconcilerio-ducks.yaml"
          ${KO} resolve --platform ${KO_PLATFORMS} -f config/ducks-runtime.yaml >> "${scratch}/config/reconcilerio-ducks.yaml"

          ${KBLD} --imgpkg-lock-output "${scratch}/.imgpkg/images.yml" \
            -f "${scratch}/config/reconcilerio-ducks.yaml" \
            > /dev/null
        echo "##[endgroup]"

        echo "##[group]Create bundle"
          ${IMGPKG} push -f "${scratch}" -b "${BUNDLE}"
          ${IMGPKG} copy -b "${BUNDLE}" --to-tar reconcilerio-ducks-bundle.tar
        echo "##[endgroup]"
    - uses: actions/upload-artifact@v7
      with:
        name: reconcilerio-ducks-bundle.tar
        path: reconcilerio-ducks-bundle.tar
        retention-days: 7

  acceptance:
    name: Acceptance Test
    needs: stage
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
        - kubernetes: v1.37
        - kubernetes: v1.36
        - kubernetes: v1.35
        - kubernetes: v1.34
        - kubernetes: v1.33
    env:
      REGISTRY_NAME: registry.local
      BUNDLE: registry.local/bundle
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache-dependency-path: '**/*.sum'
    - name: OCI Registry
      uses: reconcilerio/registry@v1
      id: registry
      with:
        hostname: ${{ env.REGISTRY_NAME }}
    - name: Kind cluster
      uses: reconcilerio/kind@main
      with:
        kubernetes-version: ${{ matrix.kubernetes }}
        registry: ${{ steps.registry.outputs.registry }}
        registry-ca: ${{ steps.registry.outputs.tls-ca }}
    - name: Download staged bundle
      uses: actions/download-artifact@v8
      with:
        name: reconcilerio-ducks-bundle.tar
    - name: Relocate bundle
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail

        ${IMGPKG} copy --tar reconcilerio-ducks-bundle.tar --to-repo "${BUNDLE}"
        mkdir -p bundle
        ${IMGPKG} pull -b "${BUNDLE}" -o bundle
    - name: Deploy
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail

        echo "##[group]Create namespace"
          kubectl create ns apps
        echo "##[endgroup]"
        echo "##[group]Deploy cert-manager"
          ${KAPP} deploy -a cert-manager -n apps --wait-timeout 5m -y \
            -f https://github.com/cert-manager/cert-manager/releases/download/v1.17.1/cert-manager.yaml
        echo "##[endgroup]"
        echo "##[group]Deploy reconcilerio-ducks"
          ${KAPP} deploy -a reconcilerio-ducks -n apps --wait-timeout 5m -y \
            -f <(${KBLD} -f bundle/.imgpkg/images.yml -f bundle/config)
        echo "##[endgroup]"

    - name: Delete Gracefully
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail

        echo "##[group]Delete reconcilerio-ducks"
          ${KAPP} delete -a reconcilerio-ducks -n apps --wait-timeout 5m -y
        echo "##[endgroup]"
        echo "##[group]Delete cert-manager"
          ${KAPP} delete -a cert-manager -n apps --wait-timeout 5m -y
        echo "##[endgroup]"
      if: always()
    - name: Cleanup cluster
      run: kind delete cluster
      if: always()

  # aggregate the unit and acceptance results into a single job
  test:
    name: Test
    needs:
    - unit
    - acceptance
    runs-on: ubuntu-latest
    steps:
    - run: echo "it passed"

  release:
    name: Release
    if: startsWith(github.ref, 'refs/tags/')
    needs:
    - test
    permissions:
      contents: write
      packages: write
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: actions/setup-go@v6
      with:
        go-version-file: go.mod
        cache-dependency-path: '**/*.sum'
    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
    - name: Download staged bundle
      uses: actions/download-artifact@v8
      with:
        name: reconcilerio-ducks-bundle.tar
    - name: Install crane
      run: |
        cd $(mktemp -d -t crane.XXXX)
        curl -L https://github.com/google/go-containerregistry/releases/download/v0.9.0/go-containerregistry_Linux_x86_64.tar.gz | tar -xz
        chmod +x ./crane
        sudo mv ./crane /usr/local/bin
        cd -
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v4
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    - name: Relocate bundle to public registry
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail

        version=${{ steps.get_version.outputs.VERSION }}

        ${IMGPKG} copy --tar reconcilerio-ducks-bundle.tar --to-repo "ghcr.io/${{ github.repository }}/bundle"
        crane tag "ghcr.io/${{ github.repository }}/bundle" "${version}"
        digest=$(crane digest "ghcr.io/${{ github.repository }}/bundle:${version}")

        scratch=$(mktemp -d -t bundle.XXXX)
        mkdir -p ${scratch}
        ${IMGPKG} pull -b "ghcr.io/${{ github.repository }}/bundle:${version}@${digest}" -o ${scratch}

        cp hack/boilerplate.yaml.txt reconcilerio-ducks.yaml
        ${KBLD} -f ${scratch}/config/reconcilerio-ducks.yaml -f ${scratch}/.imgpkg/images.yml \
          >> reconcilerio-ducks.yaml
    - name: Rename artifacts with version
      run: |
        set -o errexit
        set -o nounset
        set -o pipefail
    
        version=${{ steps.get_version.outputs.VERSION }}

        cp reconcilerio-ducks-bundle.tar reconcilerio-ducks-bundle-${version}.tar
        cp reconcilerio-ducks.yaml reconcilerio-ducks-${version}.yaml
    - name: Draft GitHub Release
      uses: softprops/action-gh-release@v3
      with:
        draft: true
        files: |
          reconcilerio-ducks-bundle-${{ steps.get_version.outputs.VERSION }}.tar
          reconcilerio-ducks-${{ steps.get_version.outputs.VERSION }}.yaml
        fail_on_unmatched_files: true
        token: ${{ secrets.GITHUB_TOKEN }}
